name: "haechi-website-deployment"
on:
  push:
    branches:
      - "master"
      - "develop"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install --legacy-peer-deps
          npm run test && npm run type-check
      - name: Notification Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: haechi-website-build
          fields: repo,commit,message,author
          mention: bob
          if_mention: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

  storybook-deployment:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.HAECHI_GITHUB_PAT }}
          submodules: recursive
      - name: Cache node_modules 📦
        uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Storybook Build
        run: |
          npm ci --legacy-peer-deps
          npm run storybook:build
      - name: Storybook Deployment (audit)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HAECHI_GITHUB_PAT }}
          publish_dir: ./packages/audit/storybook-static
          destination_dir: ./audit
      - name: Storybook Deployment (haechi)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HAECHI_GITHUB_PAT }}
          publish_dir: ./packages/haechi/storybook-static
          destination_dir: ./haechi
      - name: Storybook Deployment (henesis)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HAECHI_GITHUB_PAT }}
          publish_dir: ./packages/henesis/storybook-static
          destination_dir: ./henesis
      - name: Storybook Deployment (koda)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HAECHI_GITHUB_PAT }}
          publish_dir: ./packages/koda/storybook-static
          destination_dir: ./koda
